name: afiyetlistesi
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #animation
  lottie: ^2.7.0

  #dotted-framer
  dotted_border: ^2.1.0

  #env
  flutter_dotenv: ^5.1.0

  #image
  image_picker: ^1.0.5
  image_cropper: ^5.0.1

  #Icon
  icons_plus: ^4.0.0

  #state
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  #Google-Firebase and Service
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  
  #CUSTOM PACKAGE
  #Repository
  user_repository:
    path: packages/user_repository
  post_repository:
    path: packages/post_repository
 
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/Logo.png"
  adaptive_icon_foreground: "assets/logo/Logo_foreground.png"
  adaptive_icon_background: "#ffffff"

flutter:

  uses-material-design: true

  assets:
    - assets/picture/
    - assets/lottie/
    - .env


