name: post_repository
description: Package that manages the user post process.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #State
  equatable: ^2.0.5

  #Google-Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  #CUSTOM PACKAGE
  #Repository
  user_repository:
    path: ../user_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true




